name: Compile Standalone UnConfuserEx

on:
  workflow_dispatch: # Gives you a button to start the build manually

jobs:
  publish:
    runs-on: windows-latest

    steps:
    - name: Get Code Files
      uses: actions/checkout@v4

    - name: Set Up Modern .NET Environment
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x' # Deploys the requested version in the cloud

    - name: Build Standalone Executable
      run: dotnet publish UnConfuserEx/UnConfuserEx.csproj -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -p:PublishReadyToRun=true

    - name: Save Finished Binary
      uses: actions/upload-artifact@v4
      with:
        name: Standalone-UnConfuserEx
        path: "**/bin/Release/**/publish/UnConfuserEx.exe"
